# name es predefinido
name: test1_workflow

# trigger events
on: 
  workflow_dispatch:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  VARIABLE1: value-in-the-environment
jobs:
  # yaml indentation
  # This workflow contains a jobs con cualquier nombre. Se sabe que son jobs por la indentación
  job1:
    strategy:
      matrix:
        m_variable_name1: [1, 2]
        m_variable_name2: [matrix1, matrix2]        
    environment: production
    env:
      VARIABLE2: value-in-the-job1
      VARIABLE3: ${{secrets.SECRET1}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo "Hello, world!"
      - name: Run a multi-line script
        run: |
          echo "variables message"
          echo $VARIABLE1
          echo $VARIABLE2
          echo $VARIABLE3
          echo ${{matrix.m_variable_name1}} 
          echo ${{matrix.m_variable_name2}}
          echo "end of variables"
          
