# name es predefinido
name: test2_WF

# trigger events
on: 
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # yaml indentation
  # This workflow contains a jobs con cualquier nombre. Se sabe que son jobs por la indentación
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: test2_job1_step1
        run: echo "Hello, world test2 job1 step1!"
      - name: test2_job1_step2
        run:
          echo "test2_job1_step2"