name: testing github WF 1

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: |
        echo "Step 1 going on"
        # echo "Data from previous step $DATA"
        # echo "Data from mvn test step $DATA_MVN"
    
    - name: step2 reusing WF2
      # hacemos un uses referenciando el WF re_usado con la ruta en el dir de WFs
      uses: ./.github/workflows/wf2_resuse_able.yml
    
    - name: step3
      run: echo "Completed"
        