name: testing github WF 2

on:
  workflow_dispatch:
    branches: 
      - main
  workflow_call:
  # no se especifican ramas en un reusable WF

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: stepwf2_1
      run: echo "message from WF reusable"